# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 801b631b769bbe1361adf81fb538abcafb2d1ddcf0e1624c61f8324dad899cf742a79b2ebdf63ed03ade40fd5ff04abfa86ef0a3db601b3b9a629fedffb52425

test:
  secret_key_base: b639bbcbed86605d8c8630a9a70b223ba84d0241b017b2b1cbcc4b3316e7943d63ddf1bb18cb4393a2097337c447e415ccb65f2bacf87a9381ce3049ad80cc7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
